
[[dependencies]]
    name = "github.com/Sirupsen/logrus"
    branch = "master"

[[dependencies]]
    name = "github.com/aws/aws-sdk-go"
    branch = "master"

[[dependencies]]
    name = "github.com/boltdb/bolt"
    branch = "master"

[[dependencies]]
    name = "github.com/dgrijalva/jwt-go"
    branch = "master"

[[dependencies]]
    name = "github.com/docker/docker"
    branch = "master"

[[dependencies]]
    name = "github.com/fsouza/go-dockerclient"
    branch = "master"

[[dependencies]]
    name = "github.com/gin-gonic/gin"
    branch = "master"

[[dependencies]]
    name = "github.com/go-openapi/errors"
    branch = "master"

[[dependencies]]
    name = "github.com/go-openapi/runtime"
    branch = "master"

[[dependencies]]
    name = "github.com/go-openapi/strfmt"
    branch = "master"

[[dependencies]]
    name = "github.com/go-openapi/swag"
    branch = "master"

[[dependencies]]
    name = "github.com/iron-io/functions_go"
    branch = "master"

[[dependencies]]
    name = "github.com/iron-io/iron_go3"
    branch = "master"

[[dependencies]]
    name = "github.com/iron-io/runner"
    branch = "newdep"

[[dependencies]]
    name = "github.com/lib/pq"
    branch = "master"

[[dependencies]]
    name = "github.com/spf13/viper"
    branch = "master"

[[dependencies]]
    name = "golang.org/x/crypto"
    branch = "master"

[[dependencies]]
    name = "gopkg.in/mgo.v2"
    branch = "v2"

[[dependencies]]
    name = "gopkg.in/yaml.v2"
    branch = "v2"

[[dependencies]]
    name = "github.com/go-sql-driver/mysql"
    version = "~1.3.0"

[[dependencies]]
    name = "github.com/ccirello/supervisor"
    version = "^0.5.0"

[[dependencies]]
    name = "github.com/cactus/go-statsd-client"
    version = "^3.1.0"

[[dependencies]]
    name = "github.com/satori/go.uuid"
    version = "v1.1.0"
