
[[dependencies]]
  branch = "master"
  name = "github.com/Sirupsen/logrus"

[[dependencies]]
  branch = "master"
  name = "github.com/aws/aws-sdk-go"

[[dependencies]]
  branch = "master"
  name = "github.com/boltdb/bolt"

[[dependencies]]
  name = "github.com/cactus/go-statsd-client"
  version = "^3.1.0"

[[dependencies]]
  name = "github.com/ccirello/supervisor"
  version = ">=0.5.0, <1.0.0"

[[dependencies]]
  branch = "master"
  name = "github.com/dgrijalva/jwt-go"

[[dependencies]]
  branch = "master"
  name = "github.com/moby/moby"

[[dependencies]]
  branch = "master"
  name = "github.com/fsouza/go-dockerclient"

[[dependencies]]
  branch = "master"
  name = "github.com/gin-gonic/gin"

[[dependencies]]
  branch = "master"
  name = "github.com/go-openapi/errors"

[[dependencies]]
  branch = "master"
  name = "github.com/go-openapi/runtime"

[[dependencies]]
  branch = "master"
  name = "github.com/go-openapi/strfmt"

[[dependencies]]
  branch = "master"
  name = "github.com/go-openapi/swag"

[[dependencies]]
  name = "github.com/go-sql-driver/mysql"
  version = "~1.3.0"

[[dependencies]]
  branch = "master"
  name = "github.com/iron-io/functions_go"

[[dependencies]]
  branch = "master"
  name = "github.com/iron-io/iron_go3"

[[dependencies]]
  branch = "master"
  name = "github.com/lib/pq"

[[dependencies]]
  name = "github.com/satori/go.uuid"
  version = "v1.1.0"

[[dependencies]]
  branch = "master"
  name = "github.com/spf13/viper"

[[dependencies]]
  branch = "master"
  name = "golang.org/x/crypto"

[[dependencies]]
  branch = "v2"
  name = "gopkg.in/mgo.v2"

[[dependencies]]
  branch = "v2"
  name = "gopkg.in/yaml.v2"
